#!/usr/bin/env python3
"""Write examples/index.json: the examples this repository ships, indexed by
the decision each one makes, for the MCP server's wire_pattern prompt.

An installed MCP server has no examples/ beside it, so the prompt reads this
one file (through the same ladder as the catalogue: see data.py) and inlines
the skeleton for the pattern and language asked for. The file is derived and
never edited: each example is a catalogue row whose `evidence.path` is a file
under examples/ of this repository, and the index copies that row's slug,
title, url, patterns, languages, question types and flags beside the file's
code, verbatim. To change what it says, change the example or its row.

`status` restates the row's flags and nothing more: `not-run` when the row
carries `code-untested` (the code was read, not executed), `not-recorded`
otherwise, since the catalogue records no run either way. No dates, so the
file changes only when an example or its row does.

A code file under examples/<name>/ that no row cites is left out and named in
the log: it cannot be indexed by pattern without a row.

Stdlib only, like the rest of scripts/.

Run: python3 scripts/build_examples_index.py
     python3 scripts/build_examples_index.py --check    # exit 1 if the index is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from evidence_url import repository  # noqa: E402
from sibling_lists import SELF  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLES = "examples"
OUT = f"{EXAMPLES}/index.json"
UNTESTED = "code-untested"
# Copied from the row, in this order, when the row has them.
ROW_FIELDS = ("slug", "title", "url", "patterns", "languages", "question_types", "flags")

ABOUT = (
    "Generated by scripts/build_examples_index.py from catalog.json and examples/; do not "
    "edit. Each entry is an example this repository ships: the catalogue row whose "
    "evidence.path is its file, and the file's code. status not-run means the row carries "
    "code-untested: the code was read, not executed. not-recorded means the catalogue records "
    "no run either way."
)


def own_example(entry: dict) -> bool:
    """A row citing a file under examples/ in this repository."""
    evidence = entry.get("evidence")
    path = evidence.get("path") if isinstance(evidence, dict) else None
    if not isinstance(path, str) or not path.startswith(f"{EXAMPLES}/") or path == OUT:
        return False
    found = repository(entry.get("repo")) or repository(entry.get("url"))
    return found is not None and "/".join(found).lower() == SELF.lower()


def example(entry: dict, code: str) -> dict:
    path = entry["evidence"]["path"]
    out = {"name": path.split("/")[1], "path": path}
    out.update({key: entry[key] for key in ROW_FIELDS if entry.get(key)})
    out["status"] = "not-run" if UNTESTED in (entry.get("flags") or []) else "not-recorded"
    out["code"] = code
    return out


def build(catalog: list[dict], root: pathlib.Path | None = None) -> tuple[dict, list[str]]:
    """(the index, log lines), from the example files under `root` (this
    repository by default). A row whose file is missing is left out and logged."""
    root = root or ROOT
    entries, log = [], []
    for entry in sorted((e for e in catalog if own_example(e)), key=lambda e: (e["evidence"]["path"], e["slug"])):
        file = root / entry["evidence"]["path"]
        if not file.is_file():
            log.append(f"  left out {entry['slug']}: {entry['evidence']['path']} does not exist")
            continue
        entries.append(example(entry, file.read_text(encoding="utf-8")))
    cited = {e["path"] for e in entries}
    for file in sorted((root / EXAMPLES).glob("*/*")):
        rel = file.relative_to(root).as_posix()
        if file.is_file() and file.name != "README.md" and rel not in cited:
            log.append(f"  left out {rel}: no catalogue row cites it (evidence.path)")
    return {"about": ABOUT, "examples": entries}, log


def render(index: dict) -> str:
    return json.dumps(index, ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 instead of writing a stale index")
    args = parser.parse_args(argv)

    catalog = json.loads((ROOT / "catalog.json").read_text())
    index, log = build(catalog, ROOT)
    text = render(index)
    summary = ", ".join(f"{e['name']} ({'/'.join(e.get('patterns', []))})" for e in index["examples"])
    detail = f"{len(index['examples'])} example(s): {summary or 'none'}"
    for line in log:
        print(line)
    out = ROOT / OUT
    current = out.read_text(encoding="utf-8") if out.exists() else None
    if text == current:
        print(f"{OUT} is current ({detail})")
        return 0
    if args.check:
        print(f"error: {OUT} is stale; run python3 scripts/build_examples_index.py ({detail})", file=sys.stderr)
        return 1
    out.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({detail})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
